on:
  push:
  workflow_dispatch:


jobs:

  build:
    strategy:
      matrix:
        # arch: [x86, x64]
        arch: [x86]
      fail-fast: false


    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/ar1ip2@build
        with:
          branch: custom

          token: ${{ secrets.token }}
          arch: ${{ matrix.arch }}
